name: Download the secret spots playlist everyday

on:
  schedule:
    # This runs at 09:00 UTC every day
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gawk recode
        
    - name: Run my script
      run: bash ./download
    
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Save playlist -- $(date -d "6 days ago" -u "+%Y-%m-%d")" -a
           echo "::set-output name=push::true"
        fi

    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

